version: 0.2

env:
  variables:
    TEST_MESSAGE: Good Morning

phases:
  install:
    commands:
      - echo Entered the install phase...
      - echo ${TEST_MESSAGE}

  pre_build:
    commands:
      - echo Entered the pre_build phase...

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ./gradlew build -x test
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - build/libs/codebuild-trial-1.0.war
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/**/*'
