version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...

  pre_build:
    commands:
      - echo Entered the pre_build phase...

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - ./gradlew build -x test
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - build/libs/base-project-1.0.war
  discard-paths: yes

cache:
  paths:
    - '/root/.gradle/**/*'